page_title: GFD Viewer
description: A viewer for Game Font Data (GFD) of MT Framework
enable_smart_app_banner: false
url: https://quiple.github.io
baseurl: /gfd-viewer
your_name: Lee Minseo (Quiple)
email_address: itoupluk427@gmail.com
twitter_username: kuipuru
github_username: quiple

remote_theme: emilbaehr/automatic-app-landing-page
sass:
  style: :compressed
exclude:
  - LICENSE
  - README.md
  - CNAME
collections:
  pages:
    output: true
    permalink: /:path/
markdown: kramdown
